function SessionAnalysis(DataPath)
CurDir = fileparts(mfilename('fullpath'));
FigureFolder = fullfile(fileparts(fileparts(DataPath)),'Python Figures');
%% Settings local Figure folder
system(['python -c "'...
            'import sys;'...
            'sys.path.append(r''' CurDir ''');'...
            'from report import sessionreport;'...
            'sessionreport.showAndSaveReport()" '...
        '"' DataPath '" "' FigureFolder '" '...
        '>>"C:\BpodUser\Settings Files\plotting.txt" 2>&1']);
end